server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://cdb-evwilh1i.bj.tencentcdb.com:10049/fos?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: abcd1234
  jpa:
    properties:
      hibernate:
         dialect: org.hibernate.dialect.MySQL5Dialect

mybatis:
  configuration:
     map-underscore-to-camel-case: true

management:
  endpoint:
    shutdown:
     enabled: true
  endpoints:
     web:
       exposure:
         include: shutdown
